name: Build My Reminders APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-apk:
    runs-on: ubuntu-22.04
    timeout-minutes: 90
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"
    
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: "temurin"
        java-version: "17"
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git zip unzip libssl-dev libffi-dev python3-dev autoconf automake libtool pkg-config zlib1g-dev libncurses5-dev cmake libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libtool-bin libltdl-dev ccache
        sudo apt-get install -y libunwind-dev
        sudo apt-get install -y libgstreamer1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good
        sudo apt-get install -y libgles2-mesa-dev libglew-dev
        sudo apt-get install -y cython3
    
    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install --upgrade setuptools==58.0.0 wheel
        pip install buildozer==1.5.0
        pip install cython==0.29.33
        pip install virtualenv
        pip install sh
    
    - name: Make buildozer executable
      run: chmod +x $(which buildozer) || true
    
    - name: Accept Android SDK licenses
      run: |
        yes | sdkmanager --licenses || true
    
    - name: Clean all buildozer directories
      run: |
        rm -rf .buildozer/android/platform/build-* || true
        rm -rf ~/.buildozer || true
    
    - name: Build APK with buildozer
      run: |
        buildozer -v android debug 2>&1 | tee build.log || true
        
        # Check if gradlew failed
        if grep -q "gradlew failed" build.log; then
          echo "Gradlew failed, attempting manual fix..."
          
          # Find and fix gradlew
          GRADLEW_PATH=$(find .buildozer -name "gradlew" -type f | head -1)
          if [ -n "$GRADLEW_PATH" ]; then
            echo "Found gradlew at: $GRADLEW_PATH"
            chmod +x "$GRADLEW_PATH"
            
            # Check what's wrong with gradlew
            cd $(dirname "$GRADLEW_PATH")
            echo "Testing gradlew directly..."
            ./gradlew --version || echo "Gradlew version check failed"
            ./gradlew tasks || echo "Gradlew tasks failed"
            
            # Try running the actual command
            ./gradlew clean assembleDebug --stacktrace --info
          fi
        else
          echo "Build succeeded!"
          exit 0
        fi
      env:
        ANDROID_HOME: /usr/local/lib/android/sdk
        ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
        ANDROID_NDK_HOME: /usr/local/lib/android/sdk/ndk/27.3.13750724
        USE_PREBUILT_LIBS: '1'
        USE_CCACHE: '1'
        GRADLE_OPTS: '-Xmx4096m -Dorg.gradle.jvmargs=-Xmx4096m'
        P4A_DEBUG: '1'
    
    - name: Fix Gradle wrapper and retry on failure
      if: failure()
      run: |
        echo "Build failed, checking logs..."
        cat build.log | tail -100
        
        echo "Attempting complete rebuild with Ant fallback..."
        
        # Remove gradle completely and use ant
        rm -rf .buildozer/android/platform/build-*/dists/myreminders/gradle* || true
        
        # Modify buildozer.spec to use ant temporarily
        if [ -f buildozer.spec.bak ]; then
          cp buildozer.spec.bak buildozer.spec
        else
          cp buildozer.spec buildozer.spec.bak
        fi
        
        # Try with ant
        buildozer android debug --build-tool ant
      env:
        ANDROID_HOME: /usr/local/lib/android/sdk
        ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
        ANDROID_NDK_HOME: /usr/local/lib/android/sdk/ndk/27.3.13750724
        USE_PREBUILT_LIBS: '1'
        USE_CCACHE: '1'
        P4A_DEBUG: '1'
    
    - name: List build artifacts
      if: always()
      run: |
        echo "=== Build logs ==="
        find .buildozer -name "*.log" -type f -exec echo "--- {} ---" \; -exec cat {} \; 2>/dev/null || true
        
        echo "=== Gradle logs ==="
        find .buildozer -path "*/.gradle/*/daemon/*.log" -type f -exec echo "--- {} ---" \; -exec cat {} \; 2>/dev/null || true
        
        echo "=== APK search ==="
        echo "Listing bin directory:"
        ls -lah bin/ || echo "No bin directory found"
        echo "Finding APK files:"
        find . -name "*.apk" -type f
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: MyReminders-v2.5
        path: bin/*.apk
        if-no-files-found: error
    
    - name: Upload APK as release asset
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: MyReminders-Debug-APK
        path: bin/*.apk
