name: Build My Reminders APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-apk:
    runs-on: ubuntu-22.04
    timeout-minutes: 90
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"
    
    - name: Set up Java 17
      uses: actions/setup-java@v4
      with:
        distribution: "temurin"
        java-version: "17"
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git zip unzip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev ccache
    
    - name: Install Python dependencies
      run: |
        pip install --upgrade pip setuptools wheel
        pip install buildozer==1.5.0 cython==0.29.33
    
    - name: Accept Android SDK licenses
      run: yes | sdkmanager --licenses || true
    
    - name: Clean cache
      run: rm -rf .buildozer || true
    
    - name: Build APK
      run: buildozer -v android debug
      env:
        ANDROID_HOME: /usr/local/lib/android/sdk
        ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
    
    - name: Find and copy APK
      run: |
        mkdir -p bin
        find .buildozer -name "*.apk" -exec cp {} bin/MyReminders.apk \;
        ls -lh bin/
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: MyReminders-App
        path: bin/*.apk
